// generators/react-generator/src/templates/src/components/Link.tsx
import {
  type LinkProps as RouterLinkProps,
  Link as RouterLink,
} from "react-router";
import type { ReactNode } from "react";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

export default function Link(
  props: Omit<RouterLinkProps, "to"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
    children: ReactNode;
  },
) {
  const { to, query, children, ...restProps } = props;

  const href = () => {
    const [key, ...params] = to;
    return pageRouteMap[key]?.path(params as never, query, { prefix: false });
  };

  return (
    <RouterLink {...restProps} to={href()}>
      {children}
    </RouterLink>
  );
}

// generators/vue-generator/src/templates/src/components/Link.vue
<script setup lang="ts" generic="T extends LinkProps">
import { computed } from "vue";
import { RouterLink } from "vue-router";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

type Props = {
  to: T;
  query?: Record<string | number, unknown>;
  replace?: boolean;
  activeClass?: string;
  exactActiveClass?: string;
}

const props = defineProps<Props>();

const href = computed(() => {
  const [key, ...params] = props.to;
  return pageRouteMap[key]?.path(params as never, props.query, { prefix: false });
})

const linkProps = computed(() => ({
  ...(props.replace !== undefined ? { replace: props.replace } : {}),
  ...(props.activeClass !== undefined ? { activeClass: props.activeClass } : {}),
  ...(props.exactActiveClass !== undefined ? { exactActiveClass: props.exactActiveClass } : {}),
}))
</script>

<template>
  <RouterLink :to="href" v-bind="linkProps">
    <slot />
  </RouterLink>
</template>
