// generators/svelte-generator/src/templates/lib/app/app-tsq.svelte
<script lang="ts">
  import { type QueryClient, QueryClientProvider } from "@tanstack/svelte-query";
  import type { Snippet } from "svelte";

  import { getQueryClient } from "../query";

  let { client, children }: {
    client?: QueryClient;
    children: Snippet;
  } = $props();

  const queryClient = $derived(client ?? getQueryClient());
</script>

<QueryClientProvider client={queryClient}>
  {@render children()}
</QueryClientProvider>

// generators/react-generator/src/templates/lib/app-tsq.tsx
import { type QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { ReactNode } from "react";

import { getQueryClient } from "./query";

export const AppProvider = ({
  client,
  children,
}: {
  client?: QueryClient;
  children: ReactNode;
}) => {
  const queryClient = client ?? getQueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
}
