// generators/react-generator/src/templates/src/components/Link.tsx
import {
  type LinkProps as RouterLinkProps,
  Link as RouterLink,
} from "react-router";
import type { ReactNode } from "react";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

export default function Link(
  props: Omit<RouterLinkProps, "to"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
    children: ReactNode;
  },
) {
  const { to, query, children, ...restProps } = props;

  const href = () => {
    const [key, ...params] = to;
    return pageRouteMap[key]?.path(params as never, query, { prefix: false });
  };

  return (
    <RouterLink {...restProps} to={href()}>
      {children}
    </RouterLink>
  );
}

// generators/solid-generator/src/templates/src/components/Link.tsx
import { A, type AnchorProps } from "@solidjs/router";
import { type JSXElement, splitProps } from "solid-js";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

export default function Link(
  props: Omit<AnchorProps, "href"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
    children: JSXElement;
  },
) {
  const [knownProps, restProps] = splitProps(props, [
    "to",
    "query",
    "children",
  ]);

  const href = () => {
    const [key, ...params] = knownProps.to;
    return pageRouteMap[key]?.path(params as never, knownProps.query, { prefix: false });
  };

  return <A {...{ ...restProps, href: href() }}>{knownProps.children}</A>;
}
