// generators/mdx-generator/src/templates/src/components/Link.tsx
import { h, type JSX } from "preact";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

export default function Link(
  props: Omit<h.JSX.IntrinsicElements["a"], "href"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
  },
): JSX.Element {
  const { to, query, children, ...restProps } = props;

  const [key, ...params] = to;
  const href = pageRouteMap[key]?.base(params as never, query);

  return h("a", { ...restProps, href }, children);
}

// generators/solid-generator/src/templates/src/components/Link.tsx
import { A, type AnchorProps } from "@solidjs/router";
import { type JSXElement, splitProps } from "solid-js";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

export default function Link(
  props: Omit<AnchorProps, "href"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
    children: JSXElement;
  },
) {
  const [knownProps, restProps] = splitProps(props, [
    "to",
    "query",
    "children",
  ]);

  const href = () => {
    const [key, ...params] = knownProps.to;
    return pageRouteMap[key]?.base(params as never, knownProps.query);
  };

  return <A {...{ ...restProps, href: href() }}>{knownProps.children}</A>;
}
