// generators/solid-generator/src/templates/lib/router.tsx
import type { JSX, ParentComponent } from "solid-js";
import { Router, type RouteDefinition } from "@solidjs/router";
import type { RouterFactoryReturn } from "@kosmojs/core";
import { createRouterFactory } from "@kosmojs/core/generators";

import { base } from "{{ createImport 'libCore' }}";

export const createRouters = (
  routes: Array<RouteDefinition>,
  { app }: { app: ParentComponent },
): {
  clientRouter: () => RouterFactoryReturn<JSX.Element>;
  serverRouter: (url: URL) => RouterFactoryReturn<JSX.Element>;
} => {
  const clientRouter = () => {
    const component = (
      <Router root={app} base={base}>
        {routes}
      </Router>
    );
    return { component };
  }

  const serverRouter = (url: URL) => {
    const component = (
      <Router root={app} base={base} url={url.pathname}>
        {routes}
      </Router>
    );
    return { component };
  }

  return { clientRouter, serverRouter };
}

export default createRouterFactory<RouteDefinition, JSX.Element>();

// packages/generators/solid-generator/src/templates/src/router.tsx
import { Router } from "@solidjs/router";

import { routerFactory } from "{{ createImport 'lib' 'router' }}";
import { baseurl } from "{{ createImport 'config' }}";
import app from "./App";

export default routerFactory((routes) => {
  return {
    async clientRouter() {
      return {
        router: <Router root={app} base={baseurl}>{routes}</Router>,
        app,
      };
    },
    async serverRouter(url) {
      return {
        router: <Router root={app} base={baseurl} url={url.pathname}>{routes}</Router>,
        app,
      };
    },
  }
});
