// packages/generators/mdx-generator/src/templates/src/components/Link.tsx
import { h, type JSX } from "preact";
import { stringify } from "@kosmojs/core/fetch";

import { type LinkProps, linkMap } from "{{ createImport 'lib' 'router' }}";

export default function Link(
  props: Omit<h.JSX.IntrinsicElements["a"], "href"> & {
    to?: LinkProps;
    query?: Record<string | number, unknown>;
  },
): JSX.Element {
  const { to, query, children, ...restProps } = props;

  let href: string;

  if (to) {
    const [key, ...params] = to;
    href = linkMap[key]?.base(params as never, query) ?? "";
  } else {
    href = query ? `?${stringify(query)}` : "";
  }

  return h("a", { ...restProps, href }, children);
}

// packages/generators/solid-generator/src/templates/src/components/Link.tsx
import { A, type AnchorProps, useLocation } from "@solidjs/router";
import { type JSXElement, splitProps } from "solid-js";
import { stringify } from "@kosmojs/core/fetch";

import { unwrap } from "{{ createImport 'lib' 'unwrap' }}";
import { type LinkProps, linkMap } from "{{ createImport 'lib' 'router' }}";
import { baseurl } from "{{ createImport 'config' }}";

export default function Link(
  props: Omit<AnchorProps, "href"> & {
    to?: LinkProps;
    query?: Record<string | number, unknown>;
    children: JSXElement;
  },
) {
  const [knownProps, restProps] = splitProps(props, [
    "to",
    "query",
    "children",
  ]);

  const location = useLocation();

  const href = () => {
    if (knownProps.to) {
      const [key, ...params] = knownProps.to;
      return linkMap[key]?.base(params as never, knownProps.query);
    }
    const path = location.pathname.replace(
      new RegExp(`^${baseurl.replace(/\/+$/, "")}/`),
      "/",
    );
    return knownProps.query
      ? [path, stringify(unwrap(knownProps.query))].join("?")
      : path;
  };

  return <A {...{ ...restProps, href: href() }}>{knownProps.children}</A>;
}
