// generators/solid-generator/src/templates/src/entry/server.tsx
import { renderToString, generateHydrationScript } from "solid-js/web";

import renderFactory, { createRoutes } from "{{ createImport 'libEntry' 'server' }}";
import routerFactory from "../router";

const routes = createRoutes({ withPreload: false });
const { serverRouter } = routerFactory(routes);

export default renderFactory(() => {
  const hydrationScript = generateHydrationScript();
  return {
    async renderToString(url, { assets }) {
      const page = await serverRouter(url);
      const head = assets.reduce(
        (head, { tag }) => `${head}\n${tag}`,
        hydrationScript,
      );
      const html = renderToString(() => page);
      return { head, html };
    },
  };
});

// generators/mdx-generator/src/templates/src/entry/server.tsx
import { renderToString } from "preact-render-to-string";

import renderFactory, { createRoutes } from "{{ createImport 'libEntry' 'server' }}";
import { renderHead } from "{{ createImport 'lib' 'mdx' }}"
import routerFactory from "../router";

const routes = createRoutes();
const { serverRouter } = routerFactory(routes);

export default renderFactory(() => {
  return {
    async renderToString(url, { assets }) {
      const page = serverRouter(url);

      const head = assets.reduce(
        (head, { tag }) => `${head}\n${tag}`,
        renderHead(page?.frontmatter)
      );

      const html = page ? renderToString(page.component) : "";

      return { html, head };
    },
  };
});
