// generators/react-generator/src/templates/lib/app-tsq.tsx
import { type QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { ReactNode } from "react";

import { getQueryClient } from "./query";

export const AppProvider = ({
  client,
  children,
}: {
  client?: QueryClient;
  children: ReactNode;
}) => {
  const queryClient = client ?? getQueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
}

// generators/solid-generator/src/templates/lib/app-tsq.tsx
import type { ParentComponent } from "solid-js";
import { type QueryClient, QueryClientProvider } from "@tanstack/solid-query";

import { getQueryClient } from "./query";

export const AppProvider: ParentComponent<{ client?: QueryClient }> = (props) => {
  return (
    <QueryClientProvider client={props.client ?? getQueryClient()}>
      {props.children}
    </QueryClientProvider>
  );
};
