// generators/svelte-generator/src/templates/src/components/Link.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAnchorAttributes } from "svelte/elements";

  import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

  let {
    to,
    query,
    children,
    ...rest
  }: Omit<HTMLAnchorAttributes, "href"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
    children?: Snippet;
  } = $props();

  const href = $derived.by(() => {
    const [key, ...params] = to;
    return pageRouteMap[key]?.base(params as never, query);
  });
</script>

<a {href} {...rest}>{@render children?.()}</a>

// generators/mdx-generator/src/templates/src/components/Link.tsx
import { h, type JSX } from "preact";

import { pageRouteMap, type LinkProps } from "{{ createImport 'libCore' }}";

export default function Link(
  props: Omit<h.JSX.IntrinsicElements["a"], "href"> & {
    to: LinkProps;
    query?: Record<string | number, unknown>;
  },
): JSX.Element {
  const { to, query, children, ...restProps } = props;

  const [key, ...params] = to;
  const href = pageRouteMap[key]?.base(params as never, query);

  return h("a", { ...restProps, href }, children);
}
